language: node_js
node_js:
- '0.10'
before_install: npm install -g grunt-cli
script: grunt deploy
deploy:
  provider: s3
  access_key_id: "AKIAJ5RMM3264VMARJQQ"
  secret_access_key:
    secure: "DoLLx5daVx4BGG60BeE1TFy0tZakIr20IQuQmqL/B9ruEORujnaELpgFlD2a5w/WwD5vi65U4tuZAv/M647vtjx65G4Xtt5hLcX1Ja32JL2Dg+5O4rrzImQM8S0z4cCRyZ7KjADaDYyubyeyOBKLB95reAi44ESgVNmbsPNF4yE="
  bucket: docs.spark.io
  skip_cleanup: true
  local-dir: build
  on:
    repo: spark/docs
    branch: master
